dist: xenial
sudo: true
language: python
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
env:
  global:
  - secure: mfXRItQOMbDw9VKtKW2/9qzRHuiiRhRfBMIbau4CiJgIYNlNTOlny7nild5L/z8INnZPz/2Sjvm2bOBhaWKCAFtqZfClPwhjpaGZ8C7vFOhwdd3pknG/Ppz9jRPd/7I7bPpYkRfo8PevpNlxMhgG3nVsd4uknSf1pPUHg9dwobJM1ujQoBquKbxav8j9ZDfnRoRISw7WPmK6VQyEJjwfM2t4cStYmJev7NcceHmuBxYQnab6+7YWNqavJsR4r64gGwQCvPsndxJi4w+dSWSXTKYcWI19HKmNcHnhVbqBLZfOPIscTMN3C0LBdhO0pV2LQcJBZesAA8iGVKuIWzjhpWF90RD/2fUaTrzANcKkftv+2I1utlsR6YfTy6qvfT3VqRYaYf/jE519Yod9iWaFzMGpydnOVJvkn2RRn01kTReNDOvLBipIgYdI9dCV+5NGhHapvPMyyanHFa2zr207RZLfZc6Aa6AMkF9zSyd/0ADCPuQX8CMifMesg1w0osGE3nL90mGlaL92KJWovG7IYHAU7+KJL1xV7X6dNqumoll5qXzNwwDbN4l2ueOGaNMFT/PGUs7DbXJp5yzFpy8xeq+E/CKv8i+IQEoVwvS/XiNp5EmAQkGGjk+tNo0eKgGcmOszpeKofpX2IRjF7SeiUHFetonmdEqprv0h1YJ4VMU=
  - secure: cOEysBhwcpVob9wvwAKxnVfvlIYIKl9kzxMPhzKUYgzWfznjoPofARdXj9YLJEv6ykXAUA34PCXU73uZelPAcxh4as20mPAknaf98w76IqJcN/9FDzuIlHszFpde8JClR+u+HVdXnq26hPcA3Ld/XvyXvR4fNXD73ZYjO+txbhf5U/QcalNRyKBGDYcfItGs8zznV1L5NggyDihCrTVlpUtGlQ9KY6szg/wy1l7/OWRsKIDNqo4DbbAjGnVRtR9Ln0Racgck2sRzOn0ODPxincJWpDGmGhoZvx0l8IXUe8EKwSlxd3pkKwkjEFE9nUo0ZsKfWLEOXIwfluV0rsPRvMwDxHfVzOkELOcoCOXkoKuDSUyAPOgUz6V4Lr8hiy/YsWpLd/FYsTPlPVj0N934MYPmiJJdjrl0h9AvmMcZ9VWk0QMy6f9zsfM7CaH9sFs0f8STdYq3lg30HcByUt1NMj032zNdoItb7F3FdYZQqgGJwSJzpgE2WviUO5/FL6zWM/PssahWT0RlNbd1bn8v2fq3dhqFRN82JMlf+WHbOHkUufc7Mjfyj9/7yr/164LK//LbyBgGkz1eJT3Phqu2d7ZCXz6B3yCXG87gBJbDF7qi6Qj0n6nDFn3oVK9asjWs/UTuwTuqw1cdDrJjhan9brmPT2mOEVuCw9QKIs5nch0=
install:
- pip install --upgrade pip
- pip install --upgrade -r requirements-build.txt
script:
- python ./nb-local test
jobs:
  include:
  - stage: deploy
    python: 3.7
    script: python ./nb-local pypi
